/* Auto-generated by tools/generate_patterns.py — do not edit. */
/* Source PNGs: data/missrows.png, wrongplacerows.png, correctrows.png, empty.png */

#include <Quickdraw.h>

/* missrows.png: #....... / ........ / ........ / ........ / ....#... / ........ / ........ / ........ */
Pattern gPatMiss = { { 0x80, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00 } };
short gInvertMiss = 0;

/* wrongplacerows.png: #...#... / ........ / ..#...#. / ........ / #...#... / ........ / ..#...#. / ........ */
Pattern gPatWrongPlace = { { 0x88, 0x00, 0x22, 0x00, 0x88, 0x00, 0x22, 0x00 } };
short gInvertWrongPlace = 0;

/* correctrows.png: ######## / ######## / ######## / ######## / ######## / ######## / ######## / ######## */
Pattern gPatCorrect = { { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF } };
short gInvertCorrect = 1;

/* empty.png: ........ / ........ / ........ / ........ / ........ / ........ / ........ / ........ */
Pattern gPatEmpty = { { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } };
short gInvertEmpty = 0;

