#!/usr/bin/env python3
"""Generate packed C word tables from vendored Wordle JSON lists."""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
ANSWERS_PATH = ROOT / "data" / "targetWords.json"
DICT_PATH = ROOT / "data" / "dictionary.json"
OUT_PATH = ROOT / "words_generated.c"


def load_words(path: pathlib.Path) -> list[str]:
    words = json.loads(path.read_text(encoding="utf-8"))
    cleaned = []
    for word in words:
        w = str(word).strip().upper()
        if len(w) != 5 or not w.isalpha():
            raise SystemExit(f"invalid word in {path.name}: {word!r}")
        cleaned.append(w)
    return cleaned


def emit_array(name: str, words: list[str], out) -> None:
    out.write(f"const char {name}[][5] = {{\n")
    for i, word in enumerate(words):
        chars = ", ".join(f"'{c}'" for c in word)
        comma = "," if i + 1 < len(words) else ""
        out.write(f"    {{{chars}}}{comma}\n")
    out.write("};\n\n")


def main() -> None:
    answers = load_words(ANSWERS_PATH)
    dictionary = sorted(set(load_words(DICT_PATH)))

    with OUT_PATH.open("w", encoding="utf-8") as out:
        out.write("/* Auto-generated by tools/generate_words.py — do not edit. */\n\n")
        out.write(f"const long gAnswerCount = {len(answers)};\n")
        out.write(f"const long gDictionaryCount = {len(dictionary)};\n\n")
        emit_array("gAnswers", answers, out)
        emit_array("gDictionary", dictionary, out)

    print(f"wrote {OUT_PATH.name}: {len(answers)} answers, {len(dictionary)} dictionary")


if __name__ == "__main__":
    main()
