#!/usr/bin/env python3
"""Generate 1-bit letter bitmaps from data/letters/a.png .. z.png."""

from __future__ import annotations

import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LETTERS_DIR = ROOT / "data" / "letters"
OUT = ROOT / "letters_generated.c"

LETTER_SIZE = 16
ROW_BYTES = 2
LETTER_BYTES = LETTER_SIZE * ROW_BYTES  # 32


def apply_scanline_filter(filter_type: int, row: list[int], prev: list[int]) -> list[int]:
    if filter_type == 0:
        return row
    if filter_type == 1:
        out = row[:]
        for i in range(1, len(out)):
            out[i] = (out[i] + out[i - 1]) & 0xFF
        return out
    if filter_type == 2:
        return [(row[i] + prev[i]) & 0xFF for i in range(len(row))]
    if filter_type == 3:
        return [(row[i] + (prev[i] >> 1)) & 0xFF for i in range(len(row))]
    if filter_type == 4:
        out = row[:]
        for i in range(len(out)):
            left = out[i - 1] if i > 0 else 0
            up = prev[i]
            up_left = prev[i - 1] if i > 0 else 0
            out[i] = (out[i] + ((left + up - up_left) & 0xFF)) & 0xFF
        return out
    return row


def read_indexed_png(path: Path) -> tuple[list[list[int]], list[tuple[int, int, int, int]]]:
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"Not a PNG: {path}")

    pos = 8
    width = height = 0
    bit_depth = 0
    color_type = 0
    palette = b""
    trns = b""
    raw = b""

    while pos < len(data):
        length = struct.unpack(">I", data[pos : pos + 4])[0]
        pos += 4
        ctype = data[pos : pos + 4]
        pos += 4
        chunk = data[pos : pos + length]
        pos += length + 4

        if ctype == b"IHDR":
            width, height, bit_depth, color_type = struct.unpack(">IIBB", chunk[:10])
        elif ctype == b"PLTE":
            palette = chunk
        elif ctype == b"tRNS":
            trns = chunk
        elif ctype == b"IDAT":
            raw += chunk
        elif ctype == b"IEND":
            break

    if color_type != 3 or bit_depth != 8:
        raise ValueError(f"{path.name}: need indexed 8-bit PNG")
    if width != LETTER_SIZE or height != LETTER_SIZE:
        raise ValueError(f"{path.name}: need {LETTER_SIZE}x{LETTER_SIZE} (got {width}x{height})")
    if not palette:
        raise ValueError(f"{path.name}: missing PLTE")

    colors: list[tuple[int, int, int, int]] = []
    for i in range(len(palette) // 3):
        r, g, b = palette[i * 3], palette[i * 3 + 1], palette[i * 3 + 2]
        a = trns[i] if i < len(trns) else 255
        colors.append((r, g, b, a))

    inflated = zlib.decompress(raw)
    offset = 0
    rows: list[list[int]] = []
    prev = [0] * width
    for _ in range(height):
        filter_type = inflated[offset]
        offset += 1
        row_data = list(inflated[offset : offset + width])
        offset += width
        row_data = apply_scanline_filter(filter_type, row_data, prev)
        prev = row_data
        rows.append(row_data)

    return rows, colors


def pack_letter(rows: list[list[int]], colors: list[tuple[int, int, int, int]]) -> bytes:
    """Pack opaque non-white pixels as black bits (transparent stays clear)."""
    out = bytearray(LETTER_BYTES)
    for y, row in enumerate(rows):
        for x, index in enumerate(row):
            if index >= len(colors):
                continue
            r, g, b, a = colors[index]
            if a < 128:
                continue
            # Treat dark pixels as letter ink; ignore white ink for 1-bit Or/Bic.
            if (r + g + b) < 384:
                out[y * ROW_BYTES + (x // 8)] |= 0x80 >> (x % 8)
    return bytes(out)


def ascii_preview(bits: bytes) -> str:
    lines = []
    for y in range(LETTER_SIZE):
        chars = []
        for x in range(LETTER_SIZE):
            on = bits[y * ROW_BYTES + (x // 8)] & (0x80 >> (x % 8))
            chars.append("#" if on else ".")
        lines.append("".join(chars))
    return "\n".join(lines)


def main() -> None:
    letters: list[bytes] = []
    for i, ch in enumerate("abcdefghijklmnopqrstuvwxyz"):
        path = LETTERS_DIR / f"{ch}.png"
        if not path.exists():
            raise SystemExit(f"missing {path}")
        rows, colors = read_indexed_png(path)
        packed = pack_letter(rows, colors)
        letters.append(packed)
        if ch in ("a", "w"):
            print(f"{ch}.png:")
            print(ascii_preview(packed))
            print()

    lines = [
        "/* Auto-generated by tools/generate_letters.py — do not edit. */",
        "/* Source: data/letters/a.png .. z.png (16x16 indexed, transparent/black/white) */",
        "",
        "enum {",
        f"    kLetterGlyphSize = {LETTER_SIZE},",
        f"    kLetterRowBytes = {ROW_BYTES},",
        f"    kLetterBitmapBytes = {LETTER_BYTES}",
        "};",
        "",
        "const unsigned char gLetterBits[26][kLetterBitmapBytes] = {",
    ]

    for i, packed in enumerate(letters):
        hex_bytes = ", ".join(f"0x{b:02X}" for b in packed)
        comma = "," if i < 25 else ""
        lines.append(f"    {{ {hex_bytes} }}{comma}  /* {'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[i]} */")

    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: 26 letters, {LETTER_SIZE}x{LETTER_SIZE}")


if __name__ == "__main__":
    main()
